config/routes.rb
Rails.application.routes.draw do

  get 'rooms/:id/show' => 'rooms#show' ,as: 'rooms_show'

  mount ActionCable.server => '/cable'
  devise_for :users
  devise_for :admin_users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'home#top'

  resources :charges

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :like_notes
    end
  end

  resources :notes, only: [:show, :create, :edit, :update, :destroy] do
    member do
      get :liking_users
    end
  end

  post '/like/:note_id' => 'likes#like', as: 'like'
  delete '/unlike/:note_id' => 'likes#unlike', as: 'unlike'

  get '/about' => 'home#about'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable ,:omniauthable,:registerable,:recoverable, 
  devise :database_authenticatable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :note

end

app/models/message.rb
class Message < ApplicationRecord
belongs_to :user

after_create_commit { MessageBroadcastJob.perform_later self }

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  # Noteのデータが削除されたときに、それに紐付いたいいね！も消えるようにしてください
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user

  validates :title, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable#,:confirmable
  has_many :notes
  has_many :likes
  has_many :like_notes, through: :likes, source: :note
  has_many :messages
  validates :name, presence: true
  has_many :messages
  # deviseのvalidatableによって以下と同じバリデーションが設定されているのでコメントアウトしています
  # validates :email, presence: true, uniqueness: true

  def set_image(file)
    if !file.nil?
      file_name = file.original_filename
      File.open("public/user_images/#{file_name}", 'wb'){|f| f.write(file.read)}
      self.image = file_name
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
      

  include ApplicationHelper

  private

  def configure_permitted_parameters
 #   devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:name, :email, :role, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:sign_in) do |user|
      user.permit(:name, :password, :remember_me)
    end
    devise_parameter_sanitizer.permit(:account_update) do |user|
      user.permit(:name, :email, :role, :current_password, :password, :password_confirmation)
    end
  
  end 
  # 以下の1行は消さないでください
 # def default_url_options() {privateIp: '10.0.0.44', containerPort: '3000', languageName: 'rails'}.merge(super) end

  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def new
	end

	def create
	  # Amount in cents
	  @amount = 1000

	  customer = Stripe::Customer.create(
	    :email => params[:stripeEmail],
	    :source  => params[:stripeToken]
	  )

	  charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => @amount,
	    :description => 'プレミアムプラン',
	    :currency    => 'jpy'
	  )

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to new_charge_path
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    if user_signed_in?
      @note = Note.new
      @notes = Note.all.order(created_at: :desc)
    else
      @message = "ようこそGatebookへ！"
    end
  end
  
  def about
  end
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def like
    @note = Note.find(params[:note_id])
    like = current_user.likes.build(note_id: @note.id)
    like.save
  end

  def unlike
    # 変数noteを変数@noteに書き換えてください
    @note = Note.find(params[:note_id])
    like = current_user.likes.find_by(note_id: @note.id)
    like.destroy
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]
  before_action :set_note, only: [:show, :edit, :update, :destroy, :liking_users]

  def show
  end

  def create
    @note = current_user.notes.build(note_params)
    if @note.save
      redirect_to @note, notice: "投稿が保存されました"
    else
      @notes = Note.all.order(created_at: :desc)
      render 'home/top'
    end
  end

  def edit
  end

  def update
    if @note.update(note_params)
      redirect_to @note, notice: "投稿が更新されました"
    else
      render :edit
    end
  end

  def destroy
    @note.destroy
    redirect_to root_path
  end

  def liking_users
    @users = @note.liking_users
  end



  private

    def set_note
      @note = Note.find(params[:id])
    end

    def note_params
      params.require(:note).permit(:title, :content)
    end

    def correct_user
      note = Note.find(params[:id])
      if !current_user?(note.user)
        redirect_to root_path, alert: '許可されていないページです'
      end
    end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
  if Message.any? == true then
  	@message = Message.find(Message.last.id)
  else
  	@message = Message.all
  end
  
  # @user = User.find(params[:id])
  #  @messages = Massage.where(user_id: @user.id)
  # @messages = @user.messages
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]
  before_action :set_user, only: [:show, :edit, :update, :like_notes]
  

  def index
    @users = User.all
  end

  def show
    @notes = @user.notes
    @title = "投稿一覧"
  end

  def edit
  end

  def update
    file = params[:user][:image]
    @user.set_image(file)

    if @user.update(user_params)
      redirect_to @user, notice: 'ユーザー情報が更新されました'
    else
      render :edit
    end
  end

  def like_notes
    @notes = @user.like_notes
    @title = "いいね！一覧"
    render :show
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email)
    end

    def correct_user
      user = User.find(params[:id])
      if !current_user?(user)
        redirect_to root_path, alert: '許可されていないページです'
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user?(user)
    current_user.id == user.id
  end
  
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
  def image_for(user)
    if user.image
      image_tag "/user_images/#{user.image}", class: "profile_img"
    else
      image_tag "wanko.png", class: "profile_img"
    end
  end
  
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>1,000円</strong>!</h2>

app/views/charges/index.html.erb
<%= link_to "支払い", new_charge_path %>

app/views/charges/new.html.erb
<button id="customButton">Purchase</button>

<script>
var handler = StripeCheckout.configure({
  key: 'pk_test_HJ9DK314jl6DUjpFCKhohAcM',
  image: 'https://stripe.com/img/documentation/checkout/marketplace.png',
  locale: 'auto',
  token: function(token) {
    // You can access the token ID with `token.id`.
    // Get the token ID to your server-side code for use.
  }
});

document.getElementById('customButton').addEventListener('click', function(e) {
  // Open Checkout with further options:
  handler.open({
    name: 'Ryuji Morimoto',
    description: '2 widgets',
    currency: 'jpy',
    amount: 2000 //,zipCode:"zip"
  });
  e.preventDefault();
});

// Close Checkout on page navigation:
window.addEventListener('popstate', function() {
  handler.close();
});

</script>

app/views/home/about.html.erb
<h1>Gatebookとは？</h1>
<p>GatebookとはRuby on Railsというフレームワークを駆使した、<br>記事投稿SNSサービスです。<br>近況やつぶやきを投稿し、サービス上の友達と楽しくコミュニケーションできます。</p>

app/views/home/top.html.erb
<!-- 会員 -->
<% if user_signed_in? %>
  <aside class="sidebar">
    <%= render 'notes/form' %>
  </aside>
  <ul class="notes">
    <h2>投稿の一覧</h2>
    <%= render @notes %> 
  </ul>
<% else %>
<!-- 新規ユーザー -->
  <div class="top-wrapper">
    <%#= image_tag "gatebook_cover.png" %>
    <div class="register-wrapper">
      <h1 class="catchcopy_1"><%= @message %></h1>
      <p style="text-align: left;"><%= @message_description1 %><br><%= @message_description2 %></p>
      <%= link_to simple_format("質問に答えてマイ・カウンセラーを見つける<br>(無料)"), new_user_registration_path, class: "cv_btn" %>
    </div>
    <div class="face_image" >  
      <%= image_tag "home-phone.svg" ,:class => "phone_image" ,:style => "width:335px;margin-left:50%;" %>
      <%= video_tag "1.mp4",:autoplay => true ,:loop => true, :class => "phone_video", :style => "height:478px;width:269px;left:50%;margin-left:33px;position:absolute;top:80px;" %>
    </div>
  </div>

  <div id="service">
    <div style="width: 80%;display: block;margin: 0 auto;">
      <!-- 薄い緑色の背景色 -->
      <h1 style="font-size: 50px;">どんなサービス？</h1>
      <ul class="service_contents">
        <li class="service_1">
          <%= image_tag "service_Img1.png" ,:width => "100%;" %>
        </li>
        <li class="service_2">
          <%= image_tag "service_Img2.png" ,:width => "100%;"  %>
        </li>
        <li class="service_3">
          <%= image_tag "service_Img3.png" ,:width => "100%;"  %>
        </li>
      </ul>
      <%= image_tag "key_Img.png" ,:alt => "カギ",:style => " float:left;width: 300px;" %>
      <div style="float: right;">
        <h1 style="font-size: 50px;margin-right: 10%;">プラインバシーの保護</h1>
        <p>カウンセラーには守秘義務があります。<br>あなたの相談が第三者に漏れることはありません。安心してご相談できます。</p>    
      </div>
      <%= image_tag "convinient_Img.png" ,:alt => "便利",:style => "clear: both;float: right;width: 350px;" %>   
      <div style="float: left;">
        <h1 style="font-size: 50px;margin-right: 10%;">便利</h1>
        <p>あなたの好きな場所から相談可能です。<br>お忙しい方や、身近にカウンセリングルームが無い方にお勧めです。
        </p>    
      </div>
    </div>
  </div>
  <div id="price">
    <div style="width: 80%;display: block;margin: 0 auto;">      
      <h1 style="font-size: 50px;margin: 0px;padding-top: 20px;">料金プラン</h1>
      <%= image_tag "price_Img.png" ,:alt => "料金",:style => "width: 80%;display: block;margin: 0 auto;" %>   
    </div>
  </div>

  <div id="story">
    <div style="width: 80%;display: block;margin: 0 auto;">    
      <div class="story_1" style="text-align: center;">
        <h1>私たちの物語</h1>
        <p>このサービスの開発理由と、<br>どのようなサービスを目指しているかをご紹介します</p>
      </div>
      <div class="story_2">
        <ul>
          <li>
            <%= image_tag "story_img1.png" ,:alt => "問題",:style => "clear: both;float: left;width: 30%;" %>
            <div style="float: right;width: 40%;">
              <h1>問題</h1>
              <p>森本は、仕事の悩みを誰にも相談できずにストレスを溜め込んでいました。<br>職場の人や友人に相談するのは、恥ずかしかったためカウンセラーに相談できたらと考えていました。<br>仕事が忙しいので、オンラインで気軽に相談できるカウンセリングサービスを望んでいました。
              </p>              
            </div>
      </li>
          <li>            
            <%= image_tag "story_img2.png" ,:alt => "検討",:style => "clear: both;float: right;width: 25%;margin-right: 7%;" %>
            <div style="float: left;width: 40%;">
              <h1>検討</h1>
              <p>いくつかのカウンセリングサービスに登録し、相談に乗ってもらいましたが、<br>料金が高く、時間も短いので悩みを解決することはできませんでした。<br>その他のサービスを探しましたが、残念ながら気軽に継続的なサポートを受けられるサービスはありませんでした。
              </p>
            </div>
          </li>
          <li>                  
            <%= image_tag "story_img3.png" ,:alt => "解決策",:style => "clear: both;float: left;width: 20%;margin-left: 10%;" %>
            <div style="float: right;width: 40%;">
              <h1>解決策</h1>
              <p>森本は市場に大きな穴があることを知った後、同じジレンマに落ちいっている多くの人たちを助けるチャンスだと気づきました。<br>そこで、低価格で継続的なサポートを受けられるサービスの開発を行うことにしました。
              </p>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div style="text-align: center;">
    
      <%= link_to simple_format("質問に答えてマイ・カウンセラーを見つける<br>(無料)"), new_user_registration_path, class: "cv_btn" %>
  </div>

<footer class="footer_links">
  <div> 
    <ul style="text-align: center;margin: 0 auto;padding-bottom: 10px;">
      <li><a href="" title="会社概要">会社概要</a></li>
      <li><a href="" title="利用規約">利用規約</a></li>
      <li><a href="" title="プライバシーポリシー">プライバシーポリシー</a></li>
      <li><a href="" title="お問合せ">お問合せ</a></li>
      <li><a href="" title="特定商取引法に基づく表記">特定商取引法に基づく表記</a></li>
    </ul>
  </div>
  <div style="border-bottom: solid 1px white; width: 80%;margin: 0 auto;padding-bottom: 5px;"></div>
</footer>

<% end %>

app/views/likes/_like_links.html.erb
<% if current_user.likes.find_by(note_id: note.id) %>
  <%= link_to 'いいね！を取り消す', unlike_path(note.id), method: :delete, remote: true %>
<% else %>
  <%= link_to 'いいね！', like_path(note.id), method: :post, remote: true %>
<% end %>

app/views/likes/like.js.erb
$('#like-link').html('<%= escape_javascript(render("likes/like_links", note: @note)) %>');
$('#like-count').html('<%= @note.likes.count %>');

app/views/likes/unlike.js.erb
$('#like-link').html('<%= escape_javascript(render("likes/like_links", note: @note)) %>');
$('#like-count').html('<%= @note.likes.count %>');

app/views/messages/_message.html.erb
<% cache message do %>
  <div class="message">
    <p><%= message.content %></p>
  </div>
<% end %>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= @note.errors.count %>件のエラー:</h2>

      <ul>
        <% @note.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  タイトル
  <%= f.text_field :title, { class: "form-control title-field" } %>
  内容
  <%= f.text_area :content, { class: "form-control content-field" } %>
  <%= f.submit "保存", { class: "btn primary-btn" } %>
<% end %>

app/views/notes/_note.html.erb
<li>  
  <%= image_for(note.user) %>
  <span class="user-name">
    <%= note.user.name %>
  </span>
  <span class="content">
    <%= link_to note.title, note_path(note.id) %>

    <div>
      <small>
        <%= note.likes.count %>人がいいね！といっています
      </small>
    </div>

  </span>
  <span>
    <%= note.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
  </span>
</li>

app/views/notes/edit.html.erb
<h1>投稿を編集する</h1>
<%= render 'form' %>

app/views/notes/index.html.erb
<h1>投稿の一覧</h1>
<ul class="notes">
  <%= render @notes %>
</ul>

app/views/notes/liking_users.html.erb
<ul class='show-note'>
  <%= render @note %>
</ul>

<h2 class="heading">いいねしているユーザー一覧 </h2>
<ul class='user-list'>
  <!-- ここでパーシャルファイルを呼び出してください -->
  
    <%= render @users %>
</ul>

app/views/notes/new.html.erb
<h1>新規投稿する</h1>
<%= render 'form' %>

app/views/notes/show.html.erb
<h2>タイトル</h2>
<p><%= @note.title %></p>
<h2>内容</h2>
<p><%= @note.content %></p>

<div id="like-link">
  <%= render "likes/like_links", note: @note %>
</div>

<div>
  <small>
    <%= link_to @note.likes.count, liking_users_note_path(@note.id), id: "like-count" %>人がいいね！といっています

  </small>
</div>

<% if current_user?(@note.user) %>
  <%= link_to "編集", edit_note_path(@note.id), class: "btn edit-btn" %>
  <%= link_to "削除", note_path(@note.id), method: "delete", class: "btn destroy-btn", "data-confirm" => "本当に削除しますか？" %>
<% end %>

app/views/rooms/show.html.erb
<h1>Chat room</h1>
<div id="messages">
  <%= render @message %>
  <%=  params[:id] %>
</div>

<form>
  <label>Say something:</label><br>
  <input type="text" data-behavior="room_speaker">
  <input type="hidden" name="user_id" value="<%= params[:id] %>">
</form>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
       <p><%= @user.errors.count %>件のエラーがあります。</p>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  名前
  <%= f.text_field :name, class: "form-control name-field" %>

  メールアドレス
  <%= f.text_field :email, class: "form-control email-field" %>
  
  プロフィール画像
  <%= f.file_field :image, class: "form-control image-field" %>

  <%= f.submit '保存', class: "btn primary-btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= image_for(user) %>
  <%= link_to user.name, user %>
  <%= user.email %>
</li>

app/views/users/edit.html.erb
<h1>ユーザーの編集</h1>

<%= render 'form' %>

<%= link_to 'ユーザー一覧へ', users_path %>

app/views/users/index.html.erb
<h1 class="heading">ユーザー一覧</h1>

<ul class="user-list">
  <%= render @users %>
</ul>

app/views/users/new.html.erb
<h1>新規ユーザー作成</h1>

<%= render 'form' %>

<%= link_to '戻る', users_path %>

app/views/users/show.html.erb
<aside class="sidebar">  
  <section>
    <span class="label">プロフィール画像</span>
    <h3 class="user-info">
      <%= image_for(@user) %>
    </h3>
  </section>

  <section>
    <span class="label">ユーザー</span>
    <h3 class="user-info"><%= @user.name %></h3>
  </section>
  
  <section>
    <span class="label">メールアドレス</span>
    <h3 class="user-info"><%= @user.email %></h3>
  </section>

  <%= link_to @user.likes.count, like_notes_user_path(@user.id) %>個の投稿にいいね！しています

  <% if current_user?(@user) %>
    <section>
      <small><%= link_to 'プロフィールを編集', edit_user_path(@user) %></small>
    </section>
  <% end %>

</aside>

<ul class="notes">

  <p style="font-size: 40px;"><%= link_to "チャット", rooms_show_path %></p>
  <h2><%= @title %></h2>
  <%= render @notes %>
</ul>