config/routes.rb
Rails.application.routes.draw do

  get 'rooms/:id/show' => 'rooms#show' ,as: 'rooms_show'

  mount ActionCable.server => '/cable'
  devise_for :users
  devise_for :admin_users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'home#top'

  resources :charges

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :like_notes
    end
  end

  resources :notes, only: [:show, :create, :edit, :update, :destroy] do
    member do
      get :liking_users
    end
  end

  post '/like/:note_id' => 'likes#like', as: 'like'
  delete '/unlike/:note_id' => 'likes#unlike', as: 'unlike'

  get '/about' => 'home#about'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable ,:omniauthable,:registerable,:recoverable, 
  devise :database_authenticatable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :note

end

app/models/message.rb
class Message < ApplicationRecord
belongs_to :user

after_create_commit { MessageBroadcastJob.perform_later self }

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  # Noteのデータが削除されたときに、それに紐付いたいいね！も消えるようにしてください
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user

  validates :title, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable#,:confirmable
  has_many :notes
  has_many :likes
  has_many :like_notes, through: :likes, source: :note
  has_many :messages
  validates :name, presence: true
  has_many :messages
  # deviseのvalidatableによって以下と同じバリデーションが設定されているのでコメントアウトしています
  # validates :email, presence: true, uniqueness: true

  def set_image(file)
    if !file.nil?
      file_name = file.original_filename
      File.open("public/user_images/#{file_name}", 'wb'){|f| f.write(file.read)}
      self.image = file_name
    end
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def new
	end

	def create
	  # Amount in cents
	  @amount = 1000

	  customer = Stripe::Customer.create(
	    :email => params[:stripeEmail],
	    :source  => params[:stripeToken]
	  )

	  charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => @amount,
	    :description => 'プレミアムプラン',
	    :currency    => 'jpy'
	  )

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to new_charge_path
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    if user_signed_in?
      @note = Note.new
      @notes = Note.all.order(created_at: :desc)
    else
      @message = "ようこそGatebookへ！"
    end
  end
  
  def about
  end
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def like
    @note = Note.find(params[:note_id])
    like = current_user.likes.build(note_id: @note.id)
    like.save
  end

  def unlike
    # 変数noteを変数@noteに書き換えてください
    @note = Note.find(params[:note_id])
    like = current_user.likes.find_by(note_id: @note.id)
    like.destroy
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]
  before_action :set_note, only: [:show, :edit, :update, :destroy, :liking_users]

  def show
  end

  def create
    @note = current_user.notes.build(note_params)
    if @note.save
      redirect_to @note, notice: "投稿が保存されました"
    else
      @notes = Note.all.order(created_at: :desc)
      render 'home/top'
    end
  end

  def edit
  end

  def update
    if @note.update(note_params)
      redirect_to @note, notice: "投稿が更新されました"
    else
      render :edit
    end
  end

  def destroy
    @note.destroy
    redirect_to root_path
  end

  def liking_users
    @users = @note.liking_users
  end



  private

    def set_note
      @note = Note.find(params[:id])
    end

    def note_params
      params.require(:note).permit(:title, :content)
    end

    def correct_user
      note = Note.find(params[:id])
      if !current_user?(note.user)
        redirect_to root_path, alert: '許可されていないページです'
      end
    end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
  if Message.any? == true then
  	@message = Message.find(Message.last.id)
  else
  	@message = Message.all
  end
  
  # @user = User.find(params[:id])
  #  @messages = Massage.where(user_id: @user.id)
  # @messages = @user.messages
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]
  before_action :set_user, only: [:show, :edit, :update, :like_notes]
  

  def index
    @users = User.all
  end

  def show
    @notes = @user.notes
    @title = "投稿一覧"
  end

  def edit
  end

  def update
    file = params[:user][:image]
    @user.set_image(file)

    if @user.update(user_params)
      redirect_to @user, notice: 'ユーザー情報が更新されました'
    else
      render :edit
    end
  end

  def like_notes
    @notes = @user.like_notes
    @title = "いいね！一覧"
    render :show
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email)
    end

    def correct_user
      user = User.find(params[:id])
      if !current_user?(user)
        redirect_to root_path, alert: '許可されていないページです'
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user?(user)
    current_user.id == user.id
  end
  
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
  def image_for(user)
    if user.image
      image_tag "/user_images/#{user.image}", class: "profile_img"
    else
      image_tag "wanko.png", class: "profile_img"
    end
  end
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
  <title>気軽にカウンセリングができる - ForestBook -</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar">
    <div class="container navbar_container">
      <div id="logo"><%= link_to "ForestBook", root_path %></div>
      <% if user_signed_in? %>
        <ul class="header-right">
          <li><%= link_to "ユーザー一覧", users_path %></li>
          <li><%= link_to current_user.email, current_user %></li>
          <li><%= link_to "支払い", charges_path %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        </ul>
      <% else %>
        <ul class="header-right">
          <!-- <li><%= link_to "概要（削除予定）", about_path %></li> -->
          <li><a href="/#service">サービス内容</a></li>
          <li><a href="/#price">料金</a></li>
          <li><a href="/#story">私達の物語</a></li>
          <li><%= link_to "新規登録", new_user_registration_path %></li>
          <li><%= link_to "ログイン", new_user_session_path %></li>
        </ul>
      <% end %>
    </div>
  </header>
  
  <div class="container">
    <p class="alert alert-success"><%= notice %></p>
    <p class="alert alert-danger"><%= alert %></p>
     <%= yield %>
  </div>

  <div class="container" style="background-color: #53524E;color: white;text-align: center;" >
        &copy; ForestBook All rights reserved.
  </div>
</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
  <title>気軽にカウンセリングができる - ForestBook -</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://checkout.stripe.com/checkout.js"></script>
</head>
  <body>
    <%= yield %>

  </body>
</html>